### ISSUE TITLE
Add prefix and suffix input

### ISSUE THREAD

**Issue by Kesin11** [Kesin11/setup-job-workspace-action#32]
```
  - uses: Kesin11/setup-job-workspace-action@v1
    with:
      # You can change workspace name from default: ${workspace-yaml-name}-${job-name}
      workspace_name: foo_bar_workspace
      prefix: foo-
      suffix: -bar
```

Will create `foo-${workspace-yaml-name}-${job-name}-bar`.
It useful for adding input parameters (ex. branch name) to workspace path.
